version: "3.2"
services:
  api:
    image: fast_api
    container_name: ml_api
    build:
      context: ./api
      target: build
    ports:
      - "80:5000"
    environment:
      - API_SERVICE__MODE="prod"
    volumes:
      - ./data:/home/src/data

  # redis:
  #   image: redis:6.2.6

  # model:
  #   image: ml_service
  #   build:
  #     context: ./model
  #     target: build
  #   depends_on:
  #     - redis
  #   volumes:
  #     - ./data:/home/src/data
